### ISSUE TITLE
Can't log in / use cookie

### ISSUE THREAD

**Issue by alzyras** [Monotirg/youtube-upload#1]
Hello! 

Lovely YouTube uploader, I've looked over the code a bit :)

I had trouble using it, however. It's not possible to login to youtube in playwright chrome to export cookies (browser automation login youtube block). I've also tried exporting them with Cookie-editor and converting to playwright format, but that didn't work. It accepted the format, but the session was not logged in when the script went to youtube.

I also hardcoded the user data dir of my chrome that I use, but I figured out playwright doesn't use those sessions / cookie info from there as it was not designed this way it seems.

Soo - how do you prepare the cookies for operation, where do you export them from?

Also - why are the user data dirs needed if playwright doesn't use the authentications / etc. from them, just profile attributes and assumedly plugins?

Thank you for your reply.

**Comment by alzyras** [comment]
`    async def start(self):
        self.playwright = await async_playwright().start()
        self.context = await self.playwright.chromium.launch_persistent_context(
            user_data_dir=self.user_data_dir,
            channel="chrome",
            headless=self.headless,
            proxy=self.proxy,
            user_agent=self.user_agent,
            args=[
                "--no-sandbox",
                "--allow-profiles-outside-user-dir",
                f"--profile-directory={self.profile}",
            ],
        )

        # Load cookies from file
        with open(self.cookies_path, encoding="utf-8") as f:
            cookies = json.load(f)
            await self.context.add_cookies(cookies)

        self.logger.info("Start playwright", extra=logadapter(
            playwright_settings={
                "executable_path": self.context._impl_obj._parent.executable_path,
            },
            google_profile=self.profile
        ))

        page = await self.context.new_page()
        studio_page = YTStudioPage(page)

        language = await studio_page.get_language()

        if not (self.change_language_to_eng or language == "en"):
            msg = (f"YouTube language is '{language}', "
                   f"need to change YouTube language to English. "
                   f"Use either set change_language_to_eng = True "
                   f"or do it manually in YouTube settings.")
            raise YTError(msg)
        elif self.change_language_to_eng and not language == "en":
            await studio_page.change_language_to_eng()

        await page.close()`
        
        
The cookies were not loaded. I added this to channel.py and it works.
        
However it seems the usage of the script invalidates the session in the cookies (also in my other browser where I exported the cookies from).

**Comment by Monotirg** [comment]
Hi,

Thank you for your response. 
Yes, you are right. I forgot to add cookies to the context session.
However, even though the code you provided afterwards works, it doesn't get validated by validate_cookies method. The updated version should look like this:

```python
with open(self.cookies_path, encoding="utf-8") as f:
    self.yt_cookies = Cookies(cookies=json.loads(f.read()))
...
await self.context.add_cookies(self.yt_cookies.model_dump())
```


I will upload the new version to repository.
